/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import conexao.conectabanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import conexao.modelotabela;
import javax.swing.ListSelectionModel;

/**
 *
 * @author DannieL
 */
public class frmestado extends javax.swing.JFrame {

    conectabanco conecta = new conectabanco();

    public frmestado() {
        initComponents();

        conecta.conexao();
        preenchertabela("select * from estados order by id_estado");

        codest.setEnabled(false);
        nomest.setEnabled(false);
        siglaest.setEnabled(false);
        gravarest.setEnabled(false);
        alterarest.setEnabled(false);
        excluirest.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codest = new javax.swing.JTextField();
        nomest = new javax.swing.JTextField();
        siglaest = new javax.swing.JTextField();
        novoest = new javax.swing.JButton();
        gravarest = new javax.swing.JButton();
        alterarest = new javax.swing.JButton();
        excluirest = new javax.swing.JButton();
        cancest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablest = new javax.swing.JTable();
        primeiro = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        anterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estados");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Cód:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Sigla:");

        codest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codestActionPerformed(evt);
            }
        });

        nomest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomestActionPerformed(evt);
            }
        });

        novoest.setBackground(new java.awt.Color(255, 255, 255));
        novoest.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\new-file-icon.png")); // NOI18N
        novoest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        novoest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoestActionPerformed(evt);
            }
        });

        gravarest.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\save.png")); // NOI18N
        gravarest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gravarest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarestActionPerformed(evt);
            }
        });

        alterarest.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\alterar.png")); // NOI18N
        alterarest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alterarest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarestActionPerformed(evt);
            }
        });

        excluirest.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\delete.png")); // NOI18N
        excluirest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        excluirest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirestActionPerformed(evt);
            }
        });

        cancest.setText("Cancelar");
        cancest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancestActionPerformed(evt);
            }
        });

        tablest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablest.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tablest);

        primeiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\first.png")); // NOI18N
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        proximo.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\next.png")); // NOI18N
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        ultimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\last.png")); // NOI18N
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        anterior.setIcon(new javax.swing.ImageIcon("C:\\Users\\DannieL\\Estudos\\JAVA\\Videos\\Sistema\\previous.png")); // NOI18N
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(siglaest, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(novoest)
                                .addGap(18, 18, 18)
                                .addComponent(gravarest, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alterarest))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomest, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codest, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(excluirest, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancest)
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novoest, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gravarest, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alterarest, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirest, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primeiro)
                            .addComponent(ultimo)
                            .addComponent(anterior)
                            .addComponent(proximo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cancest)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(siglaest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(735, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codestActionPerformed

    private void gravarestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarestActionPerformed

        try {

            if (nomest.getText().equals("") || siglaest.getText().equals("")) {

                JOptionPane.showMessageDialog(nomest, "Ah campos obrigatórios, que não foram preenchidos!");
                gravarest.setEnabled(true);
                cancest.setEnabled(true);
                novoest.setEnabled(false);
                alterarest.setEnabled(false);
                excluirest.setEnabled(false);
                nomest.setEnabled(true);
                siglaest.setEnabled(true);
            } else {
                //nomest.setText("");
                //siglaest.setText("");
                nomest.setEnabled(false);
                siglaest.setEnabled(false);
                gravarest.setEnabled(false);
                alterarest.setEnabled(false);
                excluirest.setEnabled(false);
                novoest.setEnabled(true);
                cancest.setEnabled(false);

                PreparedStatement pst = conecta.conn.prepareStatement("insert into estados (nome,sigla_estado) values (?,?)");
                pst.setString(1, nomest.getText());
                pst.setString(2, siglaest.getText());
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso!");
                preenchertabela("select * from estados order by id_estado");
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Erro ao realizar Cadastro!\n Erro:" + ex);
        }


    }//GEN-LAST:event_gravarestActionPerformed

    private void nomestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomestActionPerformed

    private void excluirestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirestActionPerformed
        nomest.setEnabled(false);
        siglaest.setEnabled(false);
        gravarest.setEnabled(false);
        alterarest.setEnabled(false);
        excluirest.setEnabled(false);
        novoest.setEnabled(true);

        try {
            PreparedStatement pst = conecta.conn.prepareStatement("delete from estados where sigla_estado = ?");
            pst.setString(1, siglaest.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Registro excluido com sucesso");
            preenchertabela("select * from estados order by id_estado");
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao excluir registro" + ex);
        }


    }//GEN-LAST:event_excluirestActionPerformed

    private void novoestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoestActionPerformed

        nomest.setEnabled(true);
        siglaest.setEnabled(true);
        gravarest.setEnabled(true);
        alterarest.setEnabled(false);
        excluirest.setEnabled(false);
        novoest.setEnabled(false);
        cancest.setEnabled(true);
        nomest.setText("");
        siglaest.setText("");
        codest.setText("");

    }//GEN-LAST:event_novoestActionPerformed

    private void cancestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancestActionPerformed
        gravarest.setEnabled(false);
        novoest.setEnabled(true);
        nomest.setText("");
        siglaest.setText("");
        nomest.setEnabled(false);
        siglaest.setEnabled(false);

    }//GEN-LAST:event_cancestActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        nomest.setEnabled(true);
        alterarest.setEnabled(true);
        excluirest.setEnabled(true);

        try {

            conecta.rs.last();
            codest.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            nomest.setText(conecta.rs.getString("nome"));
            siglaest.setText(conecta.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao mostrar dados" + ex);
        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
        nomest.setEnabled(true);
        alterarest.setEnabled(true);
        excluirest.setEnabled(true);

        try {
            conecta.rs.first();
            codest.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            nomest.setText(conecta.rs.getString("nome"));
            siglaest.setText(conecta.rs.getString("sigla_estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao mostrar dados" + ex);
        }


    }//GEN-LAST:event_primeiroActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        nomest.setEnabled(true);
        alterarest.setEnabled(true);
        excluirest.setEnabled(true);
        try {

            if (conecta.rs.isFirst()) {
                conecta.rs.last();
            } else {
                conecta.rs.previous();
            }
            

            codest.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            nomest.setText(conecta.rs.getString("nome"));
            siglaest.setText(conecta.rs.getString("sigla_estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados" + ex);
        }

    }//GEN-LAST:event_anteriorActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        // TODO add your handling code here:
        nomest.setEnabled(true);
        alterarest.setEnabled(true);
        excluirest.setEnabled(true);
        try {

            if (conecta.rs.isLast()) {
                conecta.rs.first();
            } else {
                conecta.rs.next();
            }

            codest.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            nomest.setText(conecta.rs.getString("nome"));
            siglaest.setText(conecta.rs.getString("sigla_estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados" + ex);
        }
    }//GEN-LAST:event_proximoActionPerformed

    private void alterarestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarestActionPerformed
        // TODO add your handling code here:
        try {

            PreparedStatement pst = conecta.conn.prepareStatement("update estados set nome = ? where id_estado = ?");
            pst.setString(1, nomest.getText());
            pst.setInt(2, Integer.parseInt(codest.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso");
            
           int pos = conecta.rs.getRow();
            
            preenchertabela("select * from estados order by id_estado");
                
          conecta.rs.absolute(pos);
            
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao alterar" + ex);
        }
    }//GEN-LAST:event_alterarestActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conecta.executasql("select * from estados");
        
        try {
            if(conecta.rs.first()){
                codest.setText(String.valueOf(conecta.rs.getInt("id_estado")));
                nomest.setText(conecta.rs.getString("nome"));          
                siglaest.setText(conecta.rs.getString("sigla_estado"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmestado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    public void preenchertabela(String sql) {

        ArrayList dados = new ArrayList();

        String[] colunas = new String[]{"CÓDIGO", "ESTADO", "SIGLA"};

        conecta.executasql(sql);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id_estado"), conecta.rs.getString("nome"), conecta.rs.getString("sigla_estado")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Preencher Tabela" + ex);
        }

        modelotabela modelo = new modelotabela(dados, colunas);

        tablest.setModel(modelo);

        tablest.getColumnModel().getColumn(0).setPreferredWidth(110);
        tablest.getColumnModel().getColumn(0).setResizable(false);
        tablest.getColumnModel().getColumn(1).setPreferredWidth(380);
        tablest.getColumnModel().getColumn(1).setResizable(false);
        tablest.getColumnModel().getColumn(2).setPreferredWidth(165);
        tablest.getColumnModel().getColumn(2).setResizable(false);
        tablest.getTableHeader().setReorderingAllowed(false);
        tablest.setAutoResizeMode(tablest.AUTO_RESIZE_OFF);
        tablest.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmestado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmestado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarest;
    private javax.swing.JButton anterior;
    private javax.swing.JButton cancest;
    private javax.swing.JTextField codest;
    private javax.swing.JButton excluirest;
    private javax.swing.JButton gravarest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomest;
    private javax.swing.JButton novoest;
    private javax.swing.JButton primeiro;
    private javax.swing.JButton proximo;
    private javax.swing.JTextField siglaest;
    private javax.swing.JTable tablest;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
